package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Performance Lab select product should clickable")
    void generatedTest() {
        step("Open https://www.performance-lab.ru", () -> {
            step("// todo: just add selenium action");
        });

        step("product site check", () -> {
            step("// todo: just add selenium action");
        });

        step("product mobile check", () -> {
            step("// todo: just add selenium action");
        });

        step("enterprise product check", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.performance-lab.ru'", () ->
            open("https://www.performance-lab.ru"));

        step("Page title should have text 'Перфоманс Лаб - Услуги по тестированию программного обеспечения'", () -> {
            String expectedTitle = "Перфоманс Лаб - Услуги по тестированию программного обеспечения";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.performance-lab.ru'", () ->
            open("https://www.performance-lab.ru"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}